include:
  - project: cc/sre/bart
    file: /cicd-templates/base-template.yml
    ref: release/latest

stages:
  - test
  - build
  - release

variables:
  PYTHON_RELEASE: "3.11"
  PYTHON_RELEASE_WIN: "311"
  UBUNTU_RELEASE: bullseye
  CICD_SUPPORT_SCRIPTS: cicd-scripts
  PIP_INSTALL_FILE: requirements-frozen-linux.txt
  TRUNK_BRANCH: main

Lint Dockerfiles:
  stage: test
  extends: .base-test

.base-build:
  stage: build
  before_script:
    - docker login -u "$JFROG_USER_LOGIN" -p "$JFROG_USER_TOKEN" "$CC_DOCKER_REGISTRY"
    - cp $GITLAB_SERVER_CERT ./gitlab-server.crt

.dependent-build:
  extends: .base-build
  needs:
    - Build Base Image

Build Base Image:
  extends: .base-build

Build Sencha Image:
  extends: .dependent-build
  variables:
    PROJECT_CFG: project-cfg-sencha.yml

Build Scan Image:
  extends: .dependent-build
  variables:
    PROJECT_CFG: project-cfg-scan.yml

Build Linux Image:
  extends: .dependent-build
  variables:
    PROJECT_CFG: project-cfg-linux.yml

Build Dotnet Image:
  extends: .dependent-build
  variables:
    PROJECT_CFG: project-cfg-dotnet.yml
  needs:
    - Build Scan Image

Build Windows Image:
  stage: build
  extends: .base-build-windows-docker
  variables:
    PROJECT_CFG: project-cfg-win.yml
    PIP_INSTALL_FILE: requirements-frozen-windows.txt

.base-release:
  stage: release
  resource_group: bart-release

.dependent-release:
  extends: .base-release
  needs:
    - Release Base Image

Release Base Image:
  extends: .base-release

Release Sencha Image:
  extends: .dependent-release
  variables:
    PROJECT_CFG: project-cfg-sencha.yml

Release Scan Image:
  extends: .dependent-release
  variables:
    PROJECT_CFG: project-cfg-scan.yml

Release Linux Image:
  extends: .dependent-release
  variables:
    PROJECT_CFG: project-cfg-linux.yml

Release Dotnet Image:
  extends: .dependent-release
  variables:
    PROJECT_CFG: project-cfg-dotnet.yml

Release Windows Image:
  extends: .dependent-release
  variables:
    PROJECT_CFG: project-cfg-win.yml

# cSpell:ignore cicd dockerfiles sencha
