name: Vjer Build
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_BUILD_VER: "3.11"
  ARTIFACTS_DIR: artifacts
  UNIT_TEST_DIR: unit_test_results
  VJER_ENV: development
  VJER_USE_FLIT: true

jobs:
  test:
    uses: tardis4500/shared-actions/.github/workflows/vjer.yml@main
    with:
      action: test
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"
          - "3.12"

  build:
    needs: test
    uses: tardis4500/shared-actions/.github/workflows/vjer.yml@main
    with:
      action: build
      os: ubuntu-latest
      python-version: "3.11"

  install-test:
    needs: build
    uses: tardis4500/shared-actions/.github/workflows/install-test.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-action: "vjer test build release"
      test-dir: test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"
          - "3.12"

# cSpell:ignore vjer venv tardis
