name: Vjer Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - release/*
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

permissions:
  checks: write
  contents: write
  id-token: write

jobs:
  ci-cd:
    uses: arisilon/shared-actions/.github/workflows/python-cicd.yaml@main
    with:
      test-action: "vjer test build release"
    secrets: inherit
