name: Vjer Build and Release

on:
  workflow_dispatch:
    inputs:
      skip-pypi-test:
        type: boolean
  push:
    branches:
      - main
      - feature/*
      - release/*
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

permissions:
  checks: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  ci-cd:
    uses: arisilon/shared-actions/.github/workflows/python-cicd.yaml@released
    with:
      install-test-action: "vjer test build release"
      skip-pypi-test: ${{ inputs.skip-pypi-test || false }}
      vjer-local: true
    secrets: inherit

  update-change-log:
    if: (github.actor != 'github-actions[bot]') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - name: Update Changelog
        uses: arisilon/shared-actions/.github/actions/update-changelog@released
        with:
          git-commit-token: ${{ secrets.RELEASE_TOKEN }}
