name: Vjer Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - release/*
  pull_request:
    branches:
      - main
      - feature/*
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTS_DIR: artifacts
  GH_TOKEN: ${{ github.token }}
  VJER_ENV: development
  VJER_PYPROJECT_BUILD: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run Vjer test
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: test
          os: ${{ matrix.os }}
          pyproject-build: true
          python-version: ${{ matrix.python-version }}
          vjer-local: true
          use-pypi-test: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.12
          - 3.13

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run Vjer build
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: build
          os: ubuntu-latest
          pyproject-build: true
          python-version: 3.12
          vjer-local: true
          use-pypi-test: true

  install-test:
    needs: build
    uses: arisilon/shared-actions/.github/workflows/install-test.yaml@released
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test-action: "vjer test build release"
      test-dir: tests
      use-pypi-test: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.12
          - 3.13

  pre_release:
    if: (github.event_name != 'pull_request') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'feature/'))
    needs: install-test
    runs-on: ubuntu-latest
    environment: pre_release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Run Vjer build
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: pre_release
          enable-git-commit: true
          os: ubuntu-latest
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          pyproject-build: true
          python-version: 3.12
          vjer-local: true
          use-pypi-test: true

  release:
    if: (github.event_name != 'pull_request') && ((github.ref_name == 'main') || startsWith(github.ref_name, 'release/'))
    needs: pre_release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Run Vjer build
        uses: arisilon/shared-actions/.github/actions/vjer@released
        with:
          action: release
          enable-git-commit: true
          os: ubuntu-latest
          pyproject-build: true
          python-version: 3.12
          vjer-local: true

# cSpell:ignore pyproject
